### PR TITLE
Changes to modify the fitting for sncosmo

### PR DESCRIPTION
**Pull request by rbiswas4**
modified:   twinkles/refit_sncosmo.py
- Added Milky Way extinction to the model (as this should be in analyzed images).  Note that this depends on ra, dec in degrees and I have not included code to obtain them.
- Changed datamask for time to redshift dependent datamask using model min and max times.  These depend on the (t0, z) parameters  which are not actually known during analysis. So, I am imagining an iterative procedure for the moment. 

The time mask should not be required for real analysis, but is probably currently useful due to a mismatch between SNCosmo models and catsim SN models. This has to do with the behavior of the model outside the time limits within which the model is defined, and SNCosmo and catsim use different assumptions currently. In the slightly longer term, we should have a SNCosmo model that is the catsim model for this purpose, and of course in the even longer term improve the two models to have a better behavior at the tail .

### CODE REVIEW

**Comment by jchiang87** [comment]
Thanks, @rbiswas4.  I'll merge this and fix up any coding issues.   In the meantime, since you asked about the pickle file with the fit results, I've put the most recent iteration at NERSC here:

```
/global/u1/j/jchiang8/refit_results_round_2.pkl
```

I set the group to `lsst`, so I think you should be able to copy it.  If not, or if you have other questions, just let me know.

**Comment by rbiswas4** [comment]
Hi Jim,

Thanks! I was able to pull the pickle file down to my computer and work
with it!

Thanks,
Rahul

**Comment by jchiang87** [comment]
@rbiswas4 I think I've got the changes made correctly, but I need the dust maps:

```
AttributeError                            Traceback (most recent call last)
/nfs/farm/g/desc/u1/users/jchiang/desc_projects/twinkles/refit_sncosmo.py in <module>()
     31     # if thse were fixed, we should not add them to the fit_lc call
     32     model.set(t0=row.t0, z=row.z)
---> 33     dustmap = sncosmo.SFD98Map()
     34     # ra, dec in degrees from truth/DM evaluation of ra, dec
     35     ebv = dustmap.get_ebv(row.ra, row.dec)

/nfs/farm/g/desc/u1/LSST_Stack_2016-04-12/lsstsw/miniconda/opt/lsst/sncosmo/lib/python/sncosmo-1.2.0-py2.7-linux-x86_64.egg/sncosmo/dustmap.pyc in __init__(self, mapdir)
     62         if mapdir is None:
     63             mapdir = conf.sfd98_dir
---> 64         mapdir = os.path.expanduser(mapdir)
     65         mapdir = os.path.expandvars(mapdir)
     66         self.fname = os.path.join(mapdir, 'SFD_dust_4096_{0}.fits')

/nfs/farm/g/desc/u1/LSST_Stack_2016-04-12/lsstsw/miniconda/lib/python2.7/posixpath.pyc in expanduser(path)
    252     """Expand ~ and ~user constructions.  If user or $HOME is unknown,
    253     do nothing."""
--> 254     if not path.startswith('~'):
    255         return path
    256     i = path.find('/', 1)

AttributeError: 'NoneType' object has no attribute 'startswith'
> /nfs/farm/g/desc/u1/LSST_Stack_2016-04-12/lsstsw/miniconda/lib/python2.7/posixpath.py(254)expanduser()
    252     """Expand ~ and ~user constructions.  If user or $HOME is unknown,
    253     do nothing."""
--> 254     if not path.startswith('~'):
    255         return path
    256     i = path.find('/', 1)
```

I've looked at the sncosmo documentation, but I can't find any place or mechanism to obtain those FITS files.  Can you point me in the right direction?  Thanks.

**Comment by jchiang87** [comment]
@rbiswas4 Nevermind.  I downloaded the files from https://github.com/sncosmo/sncosmo.github.io

**Pull request merged**
